name: yellowstone-lightweight
favicon: null
layout_spectrum: 0.02333
typography_spectrum: 0.26333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0efed'
    - '#27201e'
    - '#c5d2c8'
    - '#725238'
    - '#aa8e6e'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
